name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: gfphoenix/cloudberry

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Get Version from Git
        id: get_version
        run: echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV

      - name: Build and push build
        uses: docker/build-push-action@v5
        with:
          context: images
          file: images/rockylinux9.Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:build-${{ env.VERSION }}
          labels: build
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push test
        uses: docker/build-push-action@v5
        with:
          context: images
          file: images/rockylinux9_test.Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test-${{ env.VERSION }}
          labels: test
          cache-from: type=gha
          cache-to: type=gha,mode=max

